In [2]:
import compile; compile.main(filename='cs.f', outbin='cs',optimization=3)

Automatic python script for compilation of f2py-wrapped EVPSC Fortran code
for an interactive python environment.

Arguments for the fixed gfortran compiler are:
-finit-local-zero
-fno-automatic
-g
-Wall
-fno-align-commons
-finit-integer=zero
-fbackslash
-finit-real=zero
-fdefault-double-8
-fdefault-real-8
f2py -c --f90exec='/usr/local/bin/gfortran' --f77exec='/usr/local/bin/gfortran' --f77flags='-finit-local-zero -fno-automatic -g -Wall -fno-align-commons -finit-integer=zero -fbackslash -finit-real=zero -fdefault-double-8 -fdefault-real-8 -O3' --f90flags='-finit-local-zero -fno-automatic -g -Wall -fno-align-commons -finit-integer=zero -fbackslash -finit-real=zero -fdefault-double-8 -fdefault-real-8 -O3' -m cs cs.f > f2py_cmp_temp


0

In [4]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [5]:
idx = np.zeros((3,3))
idx[0,0] = 1.
idx[1,1] = 1.
idx[2,2] = 1.
print idx

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [6]:
import cs

ImportError: dlopen(./cs.so, 2): Symbol not found: _add33mat_
  Referenced from: ./cs.so
  Expected in: dynamic lookup


In [4]:
rot=cs.vector_ang(u=[1,1,1], th=60.)
print rot

[[ 0.66666667 -0.33333333  0.66666667]
 [ 0.66666667  0.66666667 -0.33333333]
 [-0.33333333  0.66666667  0.66666667]]

In [5]:
rot=cs.vector_ang(u=[1,1,1], th=60.)

In [6]:
cs.reflect(th=90.)

array([[ -1.00000000e+00,   1.22460635e-16,   0.00000000e+00],
       [  1.22460635e-16,   1.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

In [7]:
cs.mirror110()

array([[  2.22044605e-16,   1.00000000e+00,   0.00000000e+00],
       [  1.00000000e+00,  -2.22044605e-16,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

In [8]:
cs.rot100_90_180_270()

(array([[  6.12303177e-17,  -1.00000000e+00,   0.00000000e+00],
       [  1.00000000e+00,   6.12303177e-17,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]]),
 array([[ -1.00000000e+00,  -1.22460635e-16,   0.00000000e+00],
       [  1.22460635e-16,  -1.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]]),
 array([[ -1.83690953e-16,   1.00000000e+00,   0.00000000e+00],
       [ -1.00000000e+00,  -1.83690953e-16,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]]))

In [9]:
print cs.cubic_rot_sym.__doc__

cubic_rot_sym - Function signature:
  h,n = cubic_rot_sym(icen)
Required arguments:
  icen : input int
Return objects:
  h : rank-3 array(&apos;d&apos;) with bounds (3,3,48)
  n : int


In [10]:
h,n=cs.cubic_rot_sym(icen=True)

In [11]:
print n

48

In [12]:
hh=h.swapaxes(0,2).swapaxes(1,2)

In [13]:
for i in range(n): 
    print "%2i \n%2i %2i %2i\n%2i %2i %2i\n%2i %2i %2i\n"%\
    (i+1,
     h[0,0,i], 
     h[0,1,i], 
     h[0,2,i], 
     h[1,0,i], 
     h[1,1,i], 
     h[1,2,i],
     h[2,0,i], 
     h[2,1,i], 
     h[2,2,i]
     )

 1 
 1  0  0
 0  1  0
 0  0  1

 2 
 0  0  1
 1  0  0
 0  1  0

 3 
 0  1  0
 0  0  1
 1  0  0

 4 
 0  1  0
 1  0  0
 0  0  1

 5 
 0  0  1
 0  1  0
 1  0  0

 6 
 1  0  0
 0  0  1
 0  1  0

 7 
 0 -1  0
 1  0  0
 0  0  1

 8 
-1  0  0
 0 -1  0
 0  0  1

 9 
 0  1  0
-1  0  0
 0  0  1

10 
 0  0  1
 0 -1  0
 1  0  0

11 
 0  0  1
-1  0  0
 0 -1  0

12 
 0  0  1
 0  1  0
-1  0  0

13 
 1  0  0
 0  0  1
 0 -1  0

14 
 0 -1  0
 0  0  1
-1  0  0

15 
-1  0  0
 0  0  1
 0  1  0

16 
 1  0  0
 0 -1  0
 0  0  1

17 
 0 -1  0
-1  0  0
 0  0  1

18 
-1  0  0
 0  1  0
 0  0  1

19 
 0  0  1
 1  0  0
 0 -1  0

20 
 0  0  1
 0 -1  0
-1  0  0

21 
 0  0  1
-1  0  0
 0  1  0

22 
 0 -1  0
 0  0  1
 1  0  0

23 
-1  0  0
 0  0  1
 0 -1  0

24 
 0  1  0
 0  0  1
-1  0  0

25 
-1  0  0
 0 -1  0
 0  0 -1

26 
 0  0 -1
-1  0  0
 0 -1  0

27 
 0 -1  0
 0  0 -1
-1  0  0

28 
 0 -1  0
-1  0  0
 0  0 -1

29 
 0  0 -1
 0 -1  0
-1  0  0

30 
-1  0  0
 0  0 -1
 0 -1  0

31 
 0  1  0
-1  0  0
 0  0 -1

32 
 1  

In [14]:
# subroutine uniqpnset is not working rightly
# It seems that it has something to do with the
# false array dimension declaration.
# But still, the pure fortran executable seems working fine.
raise IOError, 'This follow uniqpnset is buggy for ipython notebook environment.'
n=[1,0,1]; b=[1,1,1]
ipr = True
uni, n = cs.uniqpnset(n=n,b=b,isym=1,ipr=ipr)
print n
type(uni)
print uni.shape
u = uni.swapaxes(0,2)

for i in range(n): 
    print "%2i %2i %2i    %2i %2i %2i\n"%\
    (u[i,0,0], u[i,0,1], u[i,0,2], u[i,1,0], u[i,1,1], u[i,1,2])


IOError: This follow uniqpnset is buggy for ipython notebook environment.

In [32]:
cs.unitcv(miller=[2,-200,100], icrysym=1, angs=[90,90,90], cdim=[1,1,1], verbose=True)

array([ 0.00894391, -0.89439142,  0.44719571])